languageCode = "en-us"
languageName = "English"
weight = 1
title = "Brock's Blog - Data|DevOps|Cloud"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
#   dateFormat = "2 January 2006"
  dateFormat = "2006-01-02"

[params.author]
  name = "Brock B"
  headline = "Brock's Blog Data|DevOps|Cloud"
  bio = "A tech enthusiast learning through writing with a primary focus on Data, Cloud, and DevOps"
  links = [
    { github = "https://github.com/be-rock" },
    { rss = "/index.xml" },
  ]
