# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/configuration/#theme-parameters

# blowfish (default), avocado, fire, ocean, forest, princess, neon, bloody, terminal, marvel, noir, autumn, congo, slate, github and one-light
colorScheme = "blowfish" # "one-light", "github", "congo"
defaultAppearance = "light"
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true

mainSections = ["posts"]

# Auto last mod from git
autoLastmod = true

[header]
  layout = "basic"

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "profile"
#   layout = "page"
  showRecent = true
  showRecentItems = 10
  showMoreLink = true
  showMoreLinkDest = "posts"
  cardView = false

[article]
  showDate = true
  showDateUpdated = false
  showAuthor = false
  showHero = false
  showBreadcrumbs = false
  showDraftLabel = true
  showReadingTime = true
  showTableOfContents = false
  showWordCount = true
  showPagination = true
  invertPagination = false
  showTaxonomies = true
#   sharingLinks = ["linkedin", "twitter", "reddit", "email"]

[list]
  showBreadcrumbs = false
  showSummary = false
  showTableOfContents = true
  showCards = false
  groupByYear = true
  cardView = false

[sitemap]
  excludedKinds = []

[taxonomy]
  showTermCount = true
  showBreadcrumbs = false
  showTableOfContents = false
  cardView = false

[term]
  showBreadcrumbs = false
  showTableOfContents = false
  groupByYear = false
  cardView = false
