baseURL = "https://be-rock.github.io/blog/"
languageCode = "en-us"
title = "Brock's Blog on Data|DevOps|Cloud"
theme = "PaperMod"

[params]
# With `autoLastmod`, you can automatically capture the last modification date of each content file
autoLastmod = true
enableGitInfo = true
showCodeCopyButtons = true
showReadingTime = true
showWordCount = true

[params.profileMode]
enabled = true
title = "Brock's Blog Data|DevOps|Cloud"
subtitle = "A tech enthusiast learning through writing with a primary focus on Data, Cloud, and DevOps"
# imageUrl = "images/profile.jpg"
# imageTitle = "Profile image"
# imageWidth = 120
# imageHeight = 120

[[params.profileMode.buttons]]
name = "Blog Posts"
url = "posts/"

# [[params.profileMode.buttons]]
# name = "Projects"
# url = "/posts/"

[[params.socialIcons]]
name = "Github"
url = "https://github.com/be-rock"

# [[params.socialIcons]]
# name = "Linkedin"
# url = "https://www.linkedin.com/in/yourusername/"

[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 3

  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 4

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 5
    ordered = false
