baseURL: "https://be-rock.github.io/blog/"
languageCode: "en-us"
title: "Brock's Blog on Data|DevOps|Cloud"
theme: "PaperMod"

params:
  # With `autoLastmod`, you can automatically capture the last modification date of each content file
  autoLastmod: true
  enableGitInfo: true
  showBreadCrumbs: false
  showCodeCopyButtons: true
  showReadingTime: true
  showWordCount: true

  profileMode:
    enabled: true
    title: "Brock's Blog Data|DevOps|Cloud"
    subtitle: "A tech enthusiast learning through writing with a primary focus on Data, Cloud, and DevOps"
    # imageUrl: "images/profile.jpg"
    # imageTitle: "Profile image"
    # imageWidth: 120
    # imageHeight: 120

    buttons:
      - name: "Blog Posts"
        url: "posts/"

      # - name: "Projects"
      #   url: "/posts/"

  socialIcons:
    - name: "Github"
      url: "https://github.com/be-rock"

    # - name: "Linkedin"
    #   url: "https://www.linkedin.com/in/yourusername/"

menu:
  main:
    - identifier: "home"
      name: "Home"
      url: "/"
      weight: 1

    - identifier: "posts"
      name: "Posts"
      url: "/posts/"
      weight: 2

    - identifier: "tags"
      name: "Tags"
      url: "/tags/"
      weight: 3

    - identifier: "search"
      name: "Search"
      url: "/search/"
      weight: 4

    - identifier: "conversations"
      name: "Conversations"
      url: "/conversations/"
      weight: 5

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"

markup:
  tableOfContents:
    startLevel: 2
    endLevel: 5
    ordered: false
